#!/usr/bin/env php
<?php
error_reporting(E_ALL & ~E_NOTICE & ~E_DEPRECATED);

use Symfony\Component\Dotenv\Dotenv;

require 'vendor/autoload.php';

use Symfony\Component\Console\Application;
use Thecad\AdventOfCode\Commands\Create;
use Thecad\AdventOfCode\Commands\Run;
use Thecad\AdventOfCode\Commands\Test;

$application = new Application();

$application->add(new Create());
$application->add(new Run());
$application->add(new Test());

try {
    $application->run();
} catch (Exception $e) {
    dump($e->getMessage());
}
