name: Qodana - Code Inspection
on:
  workflow_dispatch:
jobs:
  code_inspection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      - uses: actions/download-artifact@v2
        id: download
        with:
          name: 'qodana-report'
          path: qodana
      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./qodana/report
          destination_dir: ./
