name: Qodana - Code Inspection
on:
  workflow_dispatch:
jobs:
  code_inspection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Qodana - Code Inspection
        uses: Jetbrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      - name: LS
        run: ls
      - uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/qodana-report
      - uses: actions/download-artifact@v2
        id: download
        with:
          name: 'artifact'
          path: qodana-report
      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./qodana/report
          destination_dir: ./
